#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd project || exit 1

# Проверка типов TypeScript
npx tsc --noEmit || exit 1

# Проверка линтинга и форматирования через lint-staged
npx lint-staged
